#include "Blue.h"


#define BLUESTR "blue"

// Blue interfaces

BLUE_DEFINE_INTERFACE( IBlueOS );
BLUE_DEFINE_INTERFACE( IBlueCallbackMan );
BLUE_DEFINE_INTERFACE( IBluePaths );
BLUE_DEFINE_INTERFACE( IMotherLode );
BLUE_DEFINE_INTERFACE( ICacheable );


// Python stuff
BLUE_DEFINE_INTERFACE( IBluePyOS );
BLUE_DEFINE_INTERFACE( IPythonEvents );


// Blue persist mechanism
BLUE_DEFINE_INTERFACE( IBlueStream );
BLUE_DEFINE_INTERFACE( IReader );
BLUE_DEFINE_INTERFACE( IWriter );
BLUE_DEFINE_INTERFACE( IFilerProperties );
BLUE_DEFINE_INTERFACE( IResFile );
BLUE_DEFINE_INTERFACE( ITaskletTimer );
BLUE_DEFINE_INTERFACE( IBlueResMan );
BLUE_DEFINE_INTERFACE( IBlueResource );
BLUE_DEFINE_INTERFACE( IBlueMemStream );

BLUE_DEFINE_INTERFACE( IBlueObjectRecycler );
BLUE_DEFINE_INTERFACE( ICcpStatisticsAccumulator );

BLUE_DEFINE_INTERFACE( IUnloadable )