if(NOT TARGET Blue)
  set(_IMPORT_PREFIX ${CMAKE_CURRENT_LIST_DIR})
  add_library(Blue SHARED IMPORTED)
  find_package(BlueExposure REQUIRED NO_CMAKE_PATH)
  find_package(CcpUtils REQUIRED NO_CMAKE_PATH)
  find_package(CURL REQUIRED NO_CMAKE_PATH)
  find_package(OpenSSL REQUIRED NO_CMAKE_PATH)
  find_package(PDM REQUIRED NO_CMAKE_PATH)
  find_package(YAML REQUIRED NO_CMAKE_PATH)
  find_package(ZLIB REQUIRED NO_CMAKE_PATH)

  set_target_properties(Blue PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES "BlueExposure;CcpCore;CcpUtils"
    INTERFACE_COMPILE_DEFINITIONS "CCP_STACKLESS=1"
  )
  if(APPLE)
    set(_PREFIX "")
    set(_SUFFIX ".so")
  else()
    set(_PREFIX ${CMAKE_STATIC_LIBRARY_PREFIX})
    set(_SUFFIX ${CMAKE_STATIC_LIBRARY_SUFFIX})
  endif()
  set_property(TARGET Blue APPEND PROPERTY IMPORTED_CONFIGURATIONS ${CMAKE_CONFIGURATION_TYPES})
  foreach(CCT ${CMAKE_CONFIGURATION_TYPES})
    string(TOLOWER ${CCT} _LCCT)
    string(TOUPPER ${CCT} _UCCT)
    set(_IMP_LOC_PROP IMPORTED_LOCATION_${_UCCT})
    set(_IMP_IMP_PROP IMPORTED_IMPLIB_${_UCCT})
    if(${_LCCT} STREQUAL "release")
    if(WIN32)
      set(_IMP_LOC_VAL ${_IMPORT_PREFIX}/bin/${CCP_PLATFORM}/${CCP_ARCHITECTURE}/${CCP_TOOLSET}/Blue.dll)
    else()
      set(_IMP_LOC_VAL ${_IMPORT_PREFIX}/${CCP_VENDOR_LIB_PATH}/Blue${_SUFFIX})
    endif()
    set(_IMP_IMP_VAL ${_IMPORT_PREFIX}/${CCP_VENDOR_LIB_PATH}/${_PREFIX}Blue${_SUFFIX})
    else()
      if(WIN32)
        set(_IMP_LOC_VAL ${_IMPORT_PREFIX}/bin/${CCP_PLATFORM}/${CCP_ARCHITECTURE}/${CCP_TOOLSET}/Blue_${_LCCT}.dll)
      else()
        set(_IMP_LOC_VAL ${_IMPORT_PREFIX}/${CCP_VENDOR_LIB_PATH}/${_PREFIX}Blue_${_LCCT}${_SUFFIX})
      endif()
    set(_IMP_IMP_VAL ${_IMPORT_PREFIX}/${CCP_VENDOR_LIB_PATH}/${_PREFIX}Blue_${_LCCT}${_SUFFIX})
    endif()
    if(NOT EXISTS ${_IMP_LOC_VAL})
    message(FATAL_ERROR "Missing Blue library ${_IMP_LOC_VAL}, is a build and perforce publish for the '${CCT}' configuration missing?")
    endif()
    if(NOT EXISTS ${_IMP_IMP_VAL})
    message(FATAL_ERROR "Missing Blue library ${_IMP_IMP_VAL}, is a build and perforce publish for the '${CCT}' configuration missing?")
    endif()
    message(DEBUG "Setting Blue property ${_IMP_LOC_PROP} to ${_IMP_LOC_VAL}")
    set_target_properties(Blue PROPERTIES ${_IMP_LOC_PROP} ${_IMP_LOC_VAL})
    message(DEBUG "Setting Blue property ${_IMP_IMP_PROP} to ${_IMP_IMP_VAL}")
    set_target_properties(Blue PROPERTIES ${_IMP_IMP_PROP} ${_IMP_IMP_VAL})
  endforeach()
endif()
